
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  luther.systems:
    name: fnb_byfn

services:

  explorerdb.luther.systems:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.luther.systems
    hostname: explorerdb.luther.systems
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - luther.systems

  explorer.luther.systems:
    image: hyperledger-explorer:latest
    container_name: explorer.luther.systems
    hostname: explorer.luther.systems
    environment:
      - DATABASE_HOST=explorerdb.luther.systems
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      - PORT=8090
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./organizations/:/tmp/crypto/
      - walletstore:/opt/explorer/wallet
    ports:
      - ${PORT}:${PORT}
    depends_on:
      explorerdb.luther.systems:
        condition: service_healthy
    networks:
      - luther.systems
